// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const edge = require('selenium-webdriver/edge');  // ✅ Import đúng ServiceBuilder
const assert = require('assert');

describe('TC2', function () {
  this.timeout(30000);
  let driver;
  let vars;

  beforeEach(async function () {
    let service = new edge.ServiceBuilder('/usr/local/bin/msedgedriver');  // ✅ Khai báo đúng ServiceBuilder
    driver = await new Builder()
      .forBrowser('MicrosoftEdge')
      .setEdgeService(service)  // ✅ Sử dụng Service Builder
      .build();

    vars = {};
  });

  afterEach(async function () {
    if (driver) {  // ✅ Kiểm tra trước khi gọi quit()
      await driver.quit();
    }
  });

  it('TC2', async function () {
    await driver.get("https://webchatonline.onrender.com/signup");
    await driver.manage().window().setRect(1920, 1032);
    await driver.findElement(By.css(".btn")).click();
    const elements = await driver.findElements(By.xpath("//div[@role='status']"));
    assert(elements.length);
    assert(await driver.findElement(By.xpath("//div[@role='status']")).getText() == "Please fill in all fields");
  });
});
